[package]
name = "http2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "^0.4"
env_logger = "^0.9.0"
tokio = { version = "^1", features = ["full"] }
warp = { git = "https://github.com/soulgarden/warp", branch = "feature/route-info" }
serde = { version = "^1.0", features = ["derive"] }
serde_derive = "^1.0"
bytes = "^1"
lapin = "^2.1"
deadpool = "^0.9"
deadpool-lapin = "^0.10"
futures = "^0.3"
thiserror = "^1"
time = "0.3.11"

[dependencies.uuid]
version = "^1.1"
features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
]

[dependencies.rmp]
version = "^0.8"

[dependencies.rmp-serde]
version = "^1.1"